/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function rsProcessRegions(videoPath: string) {
    return invoke()<null>("rs_process_regions", { videoPath })
}

export function rsSaveCurrentTime(dataPath: string, time: number) {
    return invoke()<null>("rs_save_current_time", { dataPath,time })
}

export function rsGetSettings() {
    return invoke()<AppSettings>("rs_get_settings")
}

export function rsSaveSettings(settings: AppSettings) {
    return invoke()<null>("rs_save_settings", { settings })
}

export type AppSettings = { ai: AISettings }
export type AISettings = { use_ai: boolean; base_url: string; key: string; model: string; prompt_template: string }
